#!/bin/bash

# File to check
FILE="/etc/logrotate.d/rsyslog"

# Check if the file already exists
if [ -e "$FILE" ]; then
    echo "rsyslog file already exists on logrotate config"
    exit 0
else
    # Create the file with the specified content
    cat <<EOF >"$FILE"
/var/log/cron
/var/log/maillog
/var/log/messages
/var/log/secure
/var/log/spooler
{
    missingok
    sharedscripts
    postrotate
        /usr/bin/systemctl -s HUP kill rsyslog.service >/dev/null 2>&1 || true
    endscript
}
EOF
    echo "rsyslog file created successfully on /etc/logrotate.d/"
    
    exit 0
fi
