#!/bin/bash

# File to check
FILE="/etc/logrotate.d/rsyslog"

# Check if the file already exists
if [ -e "$FILE" ]; then
    echo "rsyslog file already exists on logrotate config"
    exit 0
else
    # Create the file with the specified content
    cat <<EOF >"$FILE"
/var/log/cron
/var/log/maillog
/var/log/messages
/var/log/secure
/var/log/spooler
{
    missingok
    sharedscripts
    postrotate
        /bin/kill -HUP \`cat /var/run/syslogd.pid 2> /dev/null\` 2> /dev/null || true
    endscript
}
EOF
    echo "rsyslog file created successfully on /etc/logrotate.d/"
    
    exit 0
fi
